services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app

    env_file:
      - .env
      
    environment:
      - PYTHONUNBUFFERED=1
    command: ["streamlit", "run", "main.py"]